# Generated by Django 5.1.4 on 2025-02-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('sede', models.CharField(max_length=200)),
                ('charge', models.CharField(max_length=120)),
                ('salary', models.CharField(max_length=20)),
            ],
        ),
    ]
