# Generated by Django 5.1.4 on 2025-01-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=15)),
                ('sede', models.CharField(max_length=200)),
                ('charge', models.CharField(max_length=120)),
                ('salary', models.CharField(max_length=20)),
            ],
        ),
    ]
