# Generated by Django 5.1.4 on 2025-01-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareabasededatos_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='cedula',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
